// Generated by Translator++.
// Do not edit this file directly.
var $plugins =
[
  {
    "name": "Community_Basic",
    "status": true,
    "description": "基本的なパラメーターを設定するプラグインです。",
    "parameters": {
      "cacheLimit": "20",
      "screenWidth": "816",
      "screenHeight": "624",
      "changeWindowWidthTo": "",
      "changeWindowHeightTo": "",
      "renderingMode": "auto",
      "alwaysDash": "off"
    }
  },
  {
    "name": "MadeWithMv",
    "status": false,
    "description": "メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。",
    "parameters": {
      "Show Made With MV": "true",
      "Made with MV Image": "MadeWithMv",
      "Show Custom Splash": "false",
      "Custom Image": "",
      "Fade Out Time": "120",
      "Fade In Time": "120",
      "Wait Time": "160"
    }
  },
  {
    "name": "KMS_AccelerateFileScene",
    "status": true,
    "description": "[v0.1.0] セーブ/ロード画面の描画を高速化します。",
    "parameters": {}
  },
  {
    "name": "KMS_SaveWithSnap",
    "status": true,
    "description": "[v0.1.0] セーブ/ロード画面にスクリーンショットを追加します。",
    "parameters": {
      "Image scale": "0.15",
      "Enable JPEG": "1"
    }
  },
  {
    "name": "MPP_MoveRouteEX",
    "status": true,
    "description": "【ver.1.0】移動ルートに関するコマンド詰め合わせ。",
    "parameters": {
      "Search Limit": "12"
    }
  },
  {
    "name": "DevToolsManage",
    "status": true,
    "description": "総合開発支援プラグイン",
    "parameters": {
      "開始時に起動": "true",
      "リロードキー": "F12",
      "最前面に表示キー": "F11",
      "高速化切替キー": "F9",
      "強制戦闘勝利キー": "",
      "強制戦闘敗北キー": "",
      "強制戦闘中断キー": "",
      "スクリプト実行キー": "",
      "フリーズキー": "F10",
      "Ctrl同時押し": "false",
      "Alt同時押し": "false",
      "FPS表示": "OFF",
      "タイトルカット": "false",
      "高速開始": "false",
      "高速スピード": "2",
      "モバイル偽装": "false",
      "メニューバー表示": "true",
      "クリックメニュー": "1",
      "JSON形式セーブ": "false",
      "起動時情報出力": "true",
      "最前面で起動": "false",
      "リロード機能を使う": "true",
      "右寄せ座標": "640"
    }
  },
  {
    "name": "HTN_SaveMax",
    "status": true,
    "description": "セーブ最大数を変更します",
    "parameters": {
      "Max Quantity": "50"
    }
  },
  {
    "name": "TMMapHpGauge",
    "status": true,
    "description": "マップシーンに顔グラフィックとＨＰゲージを表示します。\r\n必要に応じてＭＰや変数などをゲージで表示することもできます。",
    "parameters": {
      "gaugeWindowX": "0",
      "gaugeWindowY": "0",
      "gaugeWindowWidth": "175",
      "gaugeWindowHeight": "64",
      "gaugeAType": "VN",
      "gaugeAX": "12",
      "gaugeAY": "12",
      "gaugeAWidth": "144",
      "gaugeAHeight": "36",
      "gaugeAFontSize": "28",
      "gaugeAParam": "9",
      "gaugeAMax": "10",
      "gaugeAName": "HP",
      "gaugeAColor": "#ff60c0 #ffa0e0",
      "gaugeBType": "",
      "gaugeBX": "12",
      "gaugeBY": "12",
      "gaugeBWidth": "144",
      "gaugeBHeight": "36",
      "gaugeBFontSize": "28",
      "gaugeBParam": "0",
      "gaugeBMax": "0",
      "gaugeBName": "BP",
      "gaugeBColor": "#ff60c0 #ffa0e0",
      "gaugeCType": "",
      "gaugeCX": "12",
      "gaugeCY": "12",
      "gaugeCWidth": "144",
      "gaugeCHeight": "36",
      "gaugeCFontSize": "28",
      "gaugeCParam": "0",
      "gaugeCMax": "0",
      "gaugeCName": "CP",
      "gaugeCColor": "#ff60c0 #ffa0e0",
      "faceOffsetX": "-4",
      "faceOffsetY": "-4",
      "stateIconMax": "4",
      "stateIconX": "156",
      "stateIconY": "24",
      "shakeTime": "20",
      "startVisible": "0",
      "collideOpacity": "128",
      "messageBusyHide": "1",
      "eventBusyHide": "1"
    }
  },
  {
    "name": "UTA_MessageSkip",
    "status": true,
    "description": "特定キーを押す事でメッセージをスキップできるようにします。",
    "parameters": {
      "Skip Key": "control",
      "Show Trace": "false"
    }
  },
  {
    "name": "HorzMenuadv",
    "status": true,
    "description": "ver1.05 ホリゾンタルなメニューコマンド構成",
    "parameters": {
      "back": "menu",
      "loadtext": "Load",
      "opacity": "255",
      "xposi": "0",
      "yposi": "430",
      "pretitle": "true"
    }
  }
];